version: '3.9'

services:
  database:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - dbvolume:/var/lib/postgresql/data
  api:
    depends_on:
      - database
    build:
      context: ./API
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    env_file:
    - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
    - .env

volumes:
  dbvolume: