version: '3.9'

services:
  database:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
  api:
    image: petaway-api
    depends_on:
      - database
    ports:
      - 5000:5000
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      DB_HOSTNAME: petaway_database
  frontend:
    image: petaway-frontend
    ports:
      - 3000:3000
    environment:
      API_HOSTNAME: petaway_api